version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-fox3x
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: fo3xdb
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: